=begin
#Get into Teaching API - V1

#  Provides a RESTful API for integrating with the Get into Teaching CRM.    The Get into Teaching (GIT) API sits in front of the GIT CRM, which uses the [Microsoft Dynamics365](https://docs.microsoft.com/en-us/dynamics365/) platform (the [Customer Engagement](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/overview) module is used for storing Candidate information and the [Marketing](https://docs.microsoft.com/en-us/dynamics365/marketing/developer/using-events-api) module for managing Events).    The GIT API aims to provide:    * Simple, task-based RESTful APIs.  * Message queueing (while the GIT CRM is offline for updates).  * Validation to ensure consistency across services writing to the GIT CRM.                          

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for GetIntoTeachingApiClient::MailingListApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MailingListApi' do
  before do
    # run before each test
    @instance = GetIntoTeachingApiClient::MailingListApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MailingListApi' do
    it 'should create an instance of MailingListApi' do
      expect(@instance).to be_instance_of(GetIntoTeachingApiClient::MailingListApi)
    end
  end

  # unit tests for add_mailing_list_member
  # Adds a new member to the mailing list.
  # Adds a new member to the mailing list. A new candidate will also be created if a matching candidate can not be found.
  # @param body Member to add to the mailing list.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_mailing_list_member test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
