=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GetIntoTeachingApiClient::CandidateIdsRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GetIntoTeachingApiClient::CandidateIdsRequest do
  let(:instance) { GetIntoTeachingApiClient::CandidateIdsRequest.new }

  describe 'test an instance of CandidateIdsRequest' do
    it 'should create an instance of CandidateIdsRequest' do
      expect(instance).to be_instance_of(GetIntoTeachingApiClient::CandidateIdsRequest)
    end
  end
  describe 'test attribute "candidate_ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
