=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GetIntoTeachingApiClient::ExchangeStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GetIntoTeachingApiClient::ExchangeStatus do
  let(:instance) { GetIntoTeachingApiClient::ExchangeStatus.new }

  describe 'test an instance of ExchangeStatus' do
    it 'should create an instance of ExchangeStatus' do
      expect(instance).to be_instance_of(GetIntoTeachingApiClient::ExchangeStatus)
    end
  end
end
