=begin
#Get into Teaching API - V1

#                             Provides a RESTful API for integrating with the Get into Teaching CRM.                             The Get into Teaching (GIT) API sits in front of the GIT CRM, which uses the [Microsoft Dynamics365](https://docs.microsoft.com/en-us/dynamics365/) platform (the [Customer Engagement](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/overview) module is used for storing Candidate information and the [Marketing](https://docs.microsoft.com/en-us/dynamics365/marketing/developer/using-events-api) module for managing Events).                             The GIT API aims to provide:                             * Simple, task-based RESTful APIs.                             * Message queueing (while the GIT CRM is offline for updates).                             * Validation to ensure consistency across services writing to the GIT CRM.                         

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GetIntoTeachingApiClient::CallbackBookingQuotasApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallbackBookingQuotasApi' do
  before do
    # run before each test
    @api_instance = GetIntoTeachingApiClient::CallbackBookingQuotasApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallbackBookingQuotasApi' do
    it 'should create an instance of CallbackBookingQuotasApi' do
      expect(@api_instance).to be_instance_of(GetIntoTeachingApiClient::CallbackBookingQuotasApi)
    end
  end

  # unit tests for get_callback_booking_quotas
  # Retrieves all callback booking quotas.
  # @param [Hash] opts the optional parameters
  # @return [Array<CallbackBookingQuota>]
  describe 'get_callback_booking_quotas test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
