=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GetIntoTeachingApiClient::PrivacyPoliciesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PrivacyPoliciesApi' do
  before do
    # run before each test
    @api_instance = GetIntoTeachingApiClient::PrivacyPoliciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PrivacyPoliciesApi' do
    it 'should create an instance of PrivacyPoliciesApi' do
      expect(@api_instance).to be_instance_of(GetIntoTeachingApiClient::PrivacyPoliciesApi)
    end
  end

  # unit tests for get_latest_privacy_policy
  # Retrieves the latest privacy policy.
  # @param [Hash] opts the optional parameters
  # @return [PrivacyPolicy]
  describe 'get_latest_privacy_policy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_privacy_policy
  # Retrieves a privacy policy.
  # @param id The id of the privacy policy.
  # @param [Hash] opts the optional parameters
  # @return [PrivacyPolicy]
  describe 'get_privacy_policy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
