=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GetIntoTeachingApiClient::SchoolsExperienceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SchoolsExperienceApi' do
  before do
    # run before each test
    @api_instance = GetIntoTeachingApiClient::SchoolsExperienceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SchoolsExperienceApi' do
    it 'should create an instance of SchoolsExperienceApi' do
      expect(@api_instance).to be_instance_of(GetIntoTeachingApiClient::SchoolsExperienceApi)
    end
  end

  # unit tests for add_school_experience
  # Adds a school experience to a candidate.
  # @param id The id of the candidate.
  # @param candidate_school_experience School experience details to add.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_school_experience test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for exchange_access_token_for_schools_experience_sign_up
  # Exchange an access token for a full candidate sign-up.
  # Exchanges an access token for a candidate&#39;s details to pre-populate a sign-up form.
  # @param access_token The access token to exchange.
  # @param existing_candidate_request Candidate details to exchange.
  # @param [Hash] opts the optional parameters
  # @return [SchoolsExperienceSignUp]
  describe 'exchange_access_token_for_schools_experience_sign_up test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_schools_experience_candidate
  # Retrieves a candidate for the Schools Experience service.
  # @param id The id of the candidate.
  # @param [Hash] opts the optional parameters
  # @return [SchoolsExperienceSignUp]
  describe 'get_schools_experience_candidate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_schools_experience_sign_ups
  # Retrieves existing SchoolsExperienceSignUps for the candidate ids.
  # @param ids A collection of Candidate ids.
  # @param [Hash] opts the optional parameters
  # @return [Array<SchoolsExperienceSignUp>]
  describe 'get_schools_experience_sign_ups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for sign_up_schools_experience_candidate
  # Creates a new candidate for the Schools Experience service.
  # @param schools_experience_sign_up Candidate to create for the Schools Experience service.
  # @param [Hash] opts the optional parameters
  # @return [SchoolsExperienceSignUp]
  describe 'sign_up_schools_experience_candidate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
