=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GetIntoTeachingApiClient::TeachingEventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TeachingEventsApi' do
  before do
    # run before each test
    @api_instance = GetIntoTeachingApiClient::TeachingEventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeachingEventsApi' do
    it 'should create an instance of TeachingEventsApi' do
      expect(@api_instance).to be_instance_of(GetIntoTeachingApiClient::TeachingEventsApi)
    end
  end

  # unit tests for add_teaching_event_attendee
  # Adds an attendee to a teaching event.
  # Adds an attendee to a teaching event. The event must have a &#x60;web_feed_id&#x60; to accept external attendees. 
  # @param teaching_event_add_attendee Attendee details to add.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_teaching_event_attendee test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for exchange_access_token_for_teaching_event_add_attendee
  # Retrieves a pre-populated attendee for the candidate.
  # Retrieves a pre-populated TeachingEventAddAttendee for the candidate. The access token is obtained from a &#x60;POST /api/candidates/access_tokens&#x60; request. 
  # @param access_token The access token to exchange.
  # @param existing_candidate_request Candidate details to exchange.
  # @param [Hash] opts the optional parameters
  # @return [TeachingEventAddAttendee]
  describe 'exchange_access_token_for_teaching_event_add_attendee test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for exchange_unverified_request_for_teaching_event_add_attendee
  # Retrieves a pre-populated attendee for the candidate without requiring verification.
  # Retrieves a pre-populated attendee for the candidate. This mechanism should be used with caution and the candidate should be treated as \&quot;unverified\&quot; by the client. 
  # @param existing_candidate_request Candidate details to exchange.
  # @param [Hash] opts the optional parameters
  # @return [TeachingEventAddAttendee]
  describe 'exchange_unverified_request_for_teaching_event_add_attendee test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_teaching_event
  # Retrieves a teaching event.
  # @param readable_id The readable ID of the teaching event.
  # @param [Hash] opts the optional parameters
  # @return [TeachingEvent]
  describe 'get_teaching_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_teaching_events
  # Searches for teaching events.
  # Searches for teaching events. Optionally limit the results by distance (in miles) from a postcode, event type, start date, and more. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :postcode Postcode to center the search around.
  # @option opts [Integer] :radius Radius in miles to search around the postcode.
  # @option opts [Array<Integer>] :type_ids Filter by teaching event type IDs.
  # @option opts [Boolean] :online Set to true for online events, false for in-person events.
  # @option opts [Time] :start_after Filter to events starting after this date.
  # @option opts [Time] :start_before Filter to events starting before this date.
  # @option opts [Array<Integer>] :status_ids Filter by event status IDs.
  # @option opts [Array<Integer>] :accessibility_options Filter by accessibility option IDs.
  # @option opts [Integer] :quantity Maximum number of results to return.
  # @return [Array<TeachingEvent>]
  describe 'search_teaching_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upsert_teaching_event
  # Adds or updates a teaching event.
  # If the &#x60;id&#x60; is specified then the existing teaching event will be updated, otherwise a new teaching event will be created. 
  # @param teaching_event Teaching event to upsert.
  # @param [Hash] opts the optional parameters
  # @return [TeachingEvent]
  describe 'upsert_teaching_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
