name: Ruby

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: |-
          cd gem
          bundle install
    - name: Run tests
      run: |-
           cd gem
           bundle exec rake
